### ISSUE TITLE
Extract Problem

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#1]
Here's the error I'm getting when extracting the latest version.

![image](https://user-images.githubusercontent.com/14054664/122568149-5efca780-d041-11eb-8738-d88d3a3b1729.png)

I've tried running 7-zip in admin mode.
https://superuser.com/questions/1076527/7zip-cannot-create-symbolic-link-access-is-denied-to-libhdfs-so-and-libhadoop-s

Both these files below seem to only contain a single line:

```
buttons/toolbars/_buttons_toolbar.js
buttons_playlist_tools.js
```

Install issue was my own fault.
~When I extract using PeaZip successfully it doesn't load then in fb.~

~Here's the path that I'm using (I'm running a portable version)~
~`W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts`~

**Comment by regorxxx** [comment]
That's a limitation of 7zip... And since symlinks may be a problem more than a solution for other people (although I find them great) I will simply copy the original files to the root folder and done for next releases. It's a pity, but the reality is many people use 7zip, including me.

Thanks for the report. Just uploaded a "hotfix" which is just the same files without symlinks.

**Comment by stephen147** [comment]
Thanks for the fix.
