### ISSUE TITLE
Tool to scrape needed tags

### ISSUE THREAD

**Issue by Lichtenshtein** [regorxxx/Playlist-Tools-SMP#16]
Hi. Could you please recommend a tool to scrape infos for these tags?

style, key, bpm, mood

**Comment by regorxxx** [comment]
They are stated in the readmes :)

See Playlist Tools/Configuration/Readmes/Tag sources

**Comment by regorxxx** [comment]
KEY and BPM can be calculated within foobar with other tools/write tags 
(I will rename this menu entry since it's obviously not clear enough)

**Comment by Lichtenshtein** [comment]
> See Playlist Tools/Configuration/Readmes/Tag sources

Sorry i'm totally lost in this Picard Genre thing. MusicBrainz genres, AcousticBrainz genres - which to choose? Tons of unnecessary garbage tags that needs to be cleared somehow. No styles at all. Discogs however provides a style tag, but Picard has no plugins for it.

**Comment by regorxxx** [comment]
You can configure which tags are written to files, but that's not the default behavior. It needs some tweaking.

Picard does not make distinction between genres and styles. Most users don't care about it. You may just use genres and put everything there... it's fine. Or you may use both tags for better classification, that's up to you. 

You may use discogs, that's fine too. The biography script also retrieves genre/styles from Allmusic and Last fm

**Comment by Lichtenshtein** [comment]
I think I managed to achieve an acceptable result with Picard.

First I found a lot of useful scripts for Picard. Then I tried to correct the genre names according to the music_graph_descriptors_xxx.js file - did this for lastfm plugins as well. Then I divided the genres into the main one (it should be one), and everything else goes into subgenres with the unification and elimination of duplicates. Data on genres and subgenres are taken from Musicbrainz, AcousticBrainz, Wikidata and lastfm (for each track separately). Styles are taken from lastfm (using both existing plugins for this site), combined and filtered from duplicates. In the styles tag remains something like Female Vocal, 90s, Oldies, Synth, etc. The mood is also taken from lastfm (for each track), filtered from duplicates and combined with data from AcousticBrainz. The theme tag data is taken from the lastfmng occasions tag (but I'm not sure yet that this is correct).

![12345](https://user-images.githubusercontent.com/13855295/194303938-57f0263b-79a0-4482-92db-4ffd67393558.jpg)

It's disappointing that tagging takes a very long time. It took the whole evening for some ~80 disparate files with problematic tags. For my entire library, it may take weeks (150k files).

By the way, in the music_graph_descriptors_xxx.js file there is no data on j-rock, j-pop, russian rock, film score, anime music. How and where should they be added so that the script also takes them into account?

**Comment by regorxxx** [comment]
> 



> I think I managed to achieve an acceptable result with Picard.

Would you mind sharing those scripts? They may come handy for other users :) I already share some of them at the presets folder, but it would be great to have more related to genre/styles. (I use manual tagging for those since I don't like a genre/style value for the entire album)

**Comment by regorxxx** [comment]
> It's disappointing that tagging takes a very long time. It took the whole evening for some ~80 disparate files with problematic tags. For my entire library, it may take weeks (150k files).
Why did it take you so much?

**Comment by regorxxx** [comment]
> By the way, in the music_graph_descriptors_xxx.js file there is no data on j-rock, j-pop, russian rock, film score, anime music. How and where should they be added so that the script also takes them into account?

Customizable button\readme\user descriptors. That's the info you need. You can add all the genre/styles you want.
Customizable button\Debug and testing\... descriptors. Will open the current one and an user modifiable one.

BUT if you create a new issue about genre/styles addition, I can consider to add them to the scripts for everybody. Note a genre/style must be a real genre.  Do it here please: :)
https://github.com/regorxxx/Music-Graph

Film score would be a no, like Soundtrack, they are not indicative of any particular genre just a folksonomy tag to point to an specific type of compilation. A film score album could be rock or classical for ex (real genres). Not saying such value is useless, just that it should not be used for genre similarity. Cultural variations of genres must also be carefully analyzed, because sure Chinese Rock is different to Japanese Rock, but the cultural variation does not justify them being different genres; the same than folk at USA may be different to European Folk. But both have a Folk Pop style.

Not saying in any case I will not add those (but the Film Score), just giving you ideas. Please create an issue there and point me to youtube videos representative of those genres. Also It would be great if you can point me to similar styles, influences (Rock n Roll and Rockabilly for ex.), etc.
