### ISSUE TITLE
[BUG] Custom pool

### ISSUE THREAD

**Issue by username116** [regorxxx/Playlist-Tools-SMP#24]
I've seen two other things with Custom pool:

- `Playlist Tools` > `Pools` > `Custom pool...` only works the first time. I need to restart foobar to use it again.
- One track from each playlist is missing from the number of tracks (with the start method).

For example, I ask this:

Playlist A,5;Playlist B,8
Playlist A,ALL;Playlist B,ALL
Playlist A,start;Playlist B,start
Playlist C
%PLAYLIST_INDEX%

The result is 11 tracks in Playlist C. It should be 13.

The console says that:

Playlist Tools Pools: source -> Playlist A
Playlist Tools Pools: pool size -> 4 (29) tracks
Playlist Tools Pools: source -> Playlist B
Playlist Tools Pools: pool size -> 7 (35) tracks
Playlist Tools Pools: sorting (%PLAYLIST_INDEX%)
Playlist Tools Pools: playlist -> Playlist C: 11 tracks

**Comment by regorxxx** [comment]
About your results, it should not be 13, since duplicates are always removed. The number of tracks is just a desired number, it may be lower if there are no results or there are duplicates, by path, TF or regExp.

For ex:
![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/795caba7-82aa-473f-9593-6ee63303d838)

![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/9c6cd92a-775d-4503-adc2-19e069e692e4)

![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/ae1afe75-1b78-4ac1-97fd-6d59572b4f10)

![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/ae4dc3b9-626d-4a2f-a853-0aabd362e40b)

![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/e0841ed5-1757-40fe-b747-16b46307b6b1)

**Comment by regorxxx** [comment]
Have changed the logs to better show what's going on:
![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/83307074/878e7b43-2737-49e9-977c-c4b929564fbf)

**Comment by username116** [comment]
I did the update and the first point is solved.

Thanks for the explanation, but there are no duplicates, either within playlists or between playlists. I've just tried again with the latest update, in a new panel so these are the default settings. But I'm not familiar with Playlist-Tools and TF and regExp rules.

<details><summary>Screenshots</summary>
<p>

![1](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/c1e03b37-13f1-4ad0-83f2-406ef5b1127b)

![2](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/80b208fe-4e9f-481c-88dc-0de446b54a94)

![3](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/5f3c9474-ad40-474a-857f-795022a766ce)

![4](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/05bf467a-37e8-40c1-9e9f-906b95f9207a)

![5](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/7bc4d71c-25c1-4e0a-bba7-176758df9b6d)

![6](https://github.com/regorxxx/Playlist-Tools-SMP/assets/108369600/9075ff41-38ce-480e-8b73-dd9fecf9a971)

</p>
</details>

**Comment by regorxxx** [comment]
I see, that looks like a bug. Was not able to reproduce it before.

**Comment by username116** [comment]
It's working fine now.

Memorized settings for the next time is good too. Thanks!
